# Generated by Django 5.2.7 on 2025-11-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.UUIDField(blank=True, editable=False, help_text='ID interno para rastreamento antes do callback', null=True, unique=True)),
                ('job_id', models.CharField(blank=True, help_text='ID do job retornado pela API no callback', max_length=255, null=True, unique=True)),
                ('to', models.JSONField(help_text='Lista de destinatários')),
                ('sender', models.CharField(help_text='Remetente do e-mail', max_length=255)),
                ('subject', models.CharField(help_text='Assunto do e-mail', max_length=255)),
                ('body', models.TextField(help_text='Corpo do e-mail')),
                ('status', models.CharField(default='pending', help_text='Status do envio: pending, success, failed', max_length=50)),
                ('details', models.TextField(blank=True, help_text='Detalhes do retorno da API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
