# Generated by Django 5.2.7 on 2025-12-02 17:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estrutura_organizacional', '0003_condutor_arquivo_cnh_condutor_foto_condutor'),
        ('veiculos', '0011_alter_maquina_foto_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relatorio', models.CharField(choices=[('abastecimento_por_secretaria', 'Abastecimento por Secretaria'), ('gastos_por_tipo_combustivel', 'Gastos por Tipo de Combustível'), ('consumo_medio_por_veiculo', 'Consumo Médio por Veículo'), ('historico_abastecimento_por_condutor', 'Histórico de Abastecimento por Condutor'), ('veiculos_por_status_e_secretaria', 'Veículos por Status e Secretaria'), ('abastecimento_mes_veiculos_km', 'Abastecimento/Mês - Veículos, KM'), ('veiculos_manutencao', 'Veículos em Manutenção'), ('veiculos_documentacao_vencida', 'Veículos com Documentação Vencida'), ('condutores_documentacao_vencida', 'Condutores com Documentação Vencida')], max_length=100, verbose_name='Tipo de Relatório')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('visualizacao', 'Visualização')], default='visualizacao', max_length=20, verbose_name='Formato')),
                ('data_inicial', models.DateField(blank=True, null=True, verbose_name='Data Inicial')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('data_geracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Geração')),
                ('numero_registros', models.PositiveIntegerField(default=0, verbose_name='Número de Registros')),
                ('filtros_aplicados', models.JSONField(blank=True, default=dict, verbose_name='Filtros Aplicados')),
                ('sessao_id', models.CharField(blank=True, max_length=100, verbose_name='ID da Sessão')),
                ('aba_id', models.CharField(blank=True, max_length=50, verbose_name='ID da Aba')),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estrutura_organizacional.condutor', verbose_name='Condutor')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estrutura_organizacional.secretaria', verbose_name='Secretaria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Histórico de Relatório',
                'verbose_name_plural': 'Histórico de Relatórios',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
