# Generated by Django 5.2.7 on 2025-11-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditlog.logentry',),
        ),
    ]
