# Generated by Django 5.2.7 on 2025-11-20 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Chave da Sessão')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora do Login')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora do Logout')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão do Usuário',
                'verbose_name_plural': 'Sessões dos Usuários',
                'ordering': ['-login_time'],
            },
        ),
    ]
