# Generated by Django 5.2.7 on 2025-11-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.hostinger.com', help_text='Servidor SMTP (ex: smtp.gmail.com, smtp.hostinger.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='Porta do servidor SMTP (ex: 587 para TLS, 465 para SSL, 25 para não criptografado)')),
                ('smtp_user', models.EmailField(help_text='Usuário/e-mail para autenticação SMTP', max_length=255)),
                ('smtp_password', models.CharField(help_text='Senha para autenticação SMTP', max_length=255)),
                ('use_tls', models.BooleanField(default=True, help_text='Usar TLS (Transport Layer Security)')),
                ('use_ssl', models.BooleanField(default=False, help_text='Usar SSL (Secure Sockets Layer)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configurações de E-mail',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_principal', models.ImageField(blank=True, help_text='Logo principal do sistema.', null=True, upload_to='configuracao/')),
                ('favicon', models.FileField(blank=True, help_text='Ícone do navegador (favicon).', null=True, upload_to='configuracao/')),
                ('logo_login', models.ImageField(blank=True, help_text='Imagem de fundo para a tela de login.', null=True, upload_to='configuracao/')),
                ('subtitulo_login', models.CharField(blank=True, help_text='Frase exibida abaixo da logo na tela de login.', max_length=200, null=True)),
                ('footer_text1', models.CharField(blank=True, help_text='Texto do rodapé (linha 1).', max_length=200, null=True)),
                ('footer_text2', models.CharField(blank=True, help_text='Texto do rodapé (linha 2).', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditlog.logentry',),
        ),
    ]
