# Generated by Django 5.2.7 on 2025-12-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='cnpj_prefeitura',
            field=models.CharField(blank=True, help_text='CNPJ da prefeitura.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='email_prefeitura',
            field=models.EmailField(blank=True, help_text='E-mail institucional da prefeitura.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='endereco_prefeitura',
            field=models.TextField(blank=True, help_text='Endereço completo da prefeitura.', null=True),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='nome_prefeitura',
            field=models.CharField(blank=True, help_text='Nome completo da prefeitura.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='telefone_prefeitura',
            field=models.CharField(blank=True, help_text='Telefone da prefeitura.', max_length=50, null=True),
        ),
    ]
