# Generated by Django 5.2.7 on 2025-11-05 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUGESTAO', 'Sugestão de Melhoria'), ('ELOGIO', 'Elogio'), ('PROBLEMA', 'Relatar um Problema Técnico'), ('OUTRO', 'Outro Assunto')], max_length=20)),
                ('mensagem', models.TextField()),
                ('pagina_origem', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
